// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { WaterLastAt, WaterLastAtTableId } from "./tables/WaterLastAt.sol";
import { MeditationLastAt, MeditationLastAtTableId } from "./tables/MeditationLastAt.sol";
import { ExerciseLastAt, ExerciseLastAtTableId } from "./tables/ExerciseLastAt.sol";
import { FocusLastAt, FocusLastAtTableId } from "./tables/FocusLastAt.sol";
